name: "ScratchAddonsNightlyBot"
description: "WIP"
author: "Norbiros"

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

runs:
  using: "composite"
  steps: 
    - run: pull-and-push.sh
      shell: bash
